---
- name: Copy docker-compose to remote hosts
  copy:
    src: "docker-compose.yaml"
    dest: "/opt/docker-compose.yaml"

- name: Deploy stack
  docker_stack:
    state: present
    name: "app"
    compose:
      - "/opt/docker-compose.yaml"
