---
- name: Install nginx
  apt:
    pkg:
      - nginx
      - nodejs
      - npm
    state: present
    update_cache: true

- name: Init nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Create dir /app
  file:
    path: /app
    state: directory

- name: Copy package.json
  copy:
    src: package.json
    dest: /app/package.json

- name: NPM install
  npm:
    path: /app
    state: present

- name: Copy index.js
  template:
    src: index.js.j2
    dest: /app/index.js
